### ISSUE TITLE
Is your Wicket-Shiro implementation ready for prime time

### ISSUE THREAD

**Issue by warrenbell** [55minutes/fiftyfive-wicket#33]
Where are you at with your Wicket-Shiro implementation ?

Thanks,

Warren Bell

**Comment by mattbrictson** [comment]
It depends on your needs, but yes, this Wicket-Shiro implementation:
- is stable
- is [documented](http://opensource.55minutes.com/apidocs/fiftyfive-wicket-shiro/4.0/index.html?fiftyfive/wicket/shiro/package-summary.html)
- is compatible with the latest Wicket 1.5.x and Shiro 1.2
- is small enough that you can understand it and change it, if you want
- has great test coverage

I'm also happy to accept pull-requests and suggestions for improvement.
